In [2]:
import numpy as np

In [3]:
np.__version__

'1.15.2'

In [4]:
import array

In [5]:
arr = array.array('i', [i for i in range(10)])

In [6]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
arr[1] = '2'

TypeError: an integer is required (got type str)

In [10]:
npsrr = np.array(arr)

In [11]:
npsrr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [14]:
nparr = np.array([i for i in range(10)])

In [15]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
nparr.dtype

dtype('int64')

In [17]:
nparr2 = np.array([1,2,3.0])

In [18]:
nparr2.dtype

dtype('float64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [25]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [26]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [27]:
np.random.randint(0,10)

2

In [28]:
np.random.seed(666)

In [29]:
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])

In [30]:
np.random.random(10)

array([0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811,
       0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823])

In [31]:
np.random.normal()

-1.0887929860091878

In [32]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x.ndim

1